---
language: python

python:
  - 3.7

install:
  - pip install mypy
  - git clone https://github.com/Shougo/denite.nvim /tmp/denite.nvim

script:
  - SRC=$(find . -name '*.py' | perl -pe 's,^\./,,')
  - |-
  RESULT=$(
    for i in $SRC; do
      export MYPYPATH=/tmp/denite.nvim/rplugin/python3:rplugin/python3
      mypy --strict $i | grep "^$i" | tee /dev/tty
    done
  )
- |-
  if [[ -n $RESULT ]]; then
    exit 1
  fi

notifications:
  slack:
    rooms:
      secure: "va0QFD1Sa7KvsB5yvcox0mIrmqNI9suTSvmKHekw2D90ijCReeuvkMNqpj8V8Kcs\
               2en75T6qrzVUqCoDjOABwX8LqK2Rn4FvGSIa860pEvPrXCV8VR3mDbxN4ZKaSZtV\
               2tZvfbvOg18Ii45/hNCYIMUp2R3mPn+axpOftzAdlYACdu1aegnheIMVjkILWIIp\
               t6pVnQKGtyZ1+zr/DxjDajuWrw9DF1HiQpvj6DjYITuyYG/koUpS57eUVOsUBYuy\
               +sUhsYQLmG9lbDOZgD+h4TZdTOLZI8C1Rv6H0y8a23FFW8CYPrYNoIwF1106BNQa\
               xVTDlvq7Fxggv+r3Ui5TSitU8ooiUuvGBXcTfqORG98jUKCLfmQirCxiesBY+jiO\
               B7k1Gqc6aXKRTxYq3iIT3UF6nSJ6DYzHO1X2P9KhLF077+h1bARzS6yzcSumdcuB\
               3Gpdd7dBp/bJkXBu2+RAXHQunDSqmfkWNaJzBYoTBbMHXbnnoLj6xZamx3JEhIOQ\
               myZfeZNh9nNehnWgrUzP5Gkd5cD7MIv9UHaY2nVno5lmxRk5SDHU6ZBiX6okvQiE\
               F+xqJrPIZKRXjaRjr4EpIkJT0MIy4yWPSe4qPkd71KBfasCBaJuLME5BNiUieFqT\
               h+pixuby//DMlNoxowP2uYlbrYuXzFh3Rzuvpuz8akU="
    on_success: never
